package com.QueueIt.capstone.API.Enums;

public enum MeetingStatus {
    FAILED_TEAM_NO_SHOW,
    FAILED_FACULTY_NO_SHOW,
    FAILED_DEFAULTED,
    ATTENDED_FACULTY_CONDUCTED,
    ATTENDED_QUEUEING_CONDUCTED,
    ATTENDED_SCHEDULE_CONDUCTED,
    SET_AUTOMATED,
    SET_MANUALLY,
    CANCELLED,
    STARTED_TEAM_INITIATED,
    STARTED_FACULTY_INITIATED,
    STARTED_AUTOMATED,
    STARTED_MANUALLY,
    FOLLOWUP_MEETING
}
