package com.QueueIt.capstone.API.Enums;

public enum MeetingStatus {
    FAILED_TEAM_NO_SHOW,
    FAILED_FACULTY_NO_SHOW,
    ATTENDED_FACULTY_CONDUCTED,
    ATTENDED_QUEUEING_CONDUCTED,
    FAILED_DEFAULTED,
    SET_AUTOMATED,
    SET_MANUALLY,
    CANCELLED,
}
